# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import re
import sphinx
import mock
# project root
sys.path.insert(0, os.path.abspath('../'))

# -- Project information -----------------------------------------------------

project = 'topology'
copyright = '2021, Javier Ramos'
author = 'Javier Ramos'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '1.0'

# -- General configuration ---------------------------------------------------
extensions = [
        'sphinx.ext.autodoc',
        'sphinx.ext.intersphinx',
        'sphinx.ext.autosummary',
        'sphinx.ext.napoleon',
        'sphinx.ext.mathjax',
        'sphinx.ext.viewcode'
]

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = False
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = False
napoleon_type_aliases = None

intersphinx_mapping = {'python': ('https://docs.python.org/3', None),
                       'numpy': ('https://docs.scipy.org/doc/numpy', None)}

autodoc_docstring_signature = True

sphinx_ver = tuple(map(int, sphinx.__version__.split('.')))
if sphinx_ver < (1,8,0):
    autodoc_default_flags = ['inherited-members']
else:
    autodoc_default_options = {'inherited-members': None}

#autodoc_mock_imports = ['numpy','h5py', 'networkx', 'scipy', 'matplotlib']
MOCK_MODULES = ['pandas', 'networkx', 'matplotlib', 'numpy', 'scipy', 'h5py', 'ext_libc', 'ext_libc.c_discriminant', 'numpy.core', 'numpy.core._multiarray_umath']
for mod_name in MOCK_MODULES:
    sys.modules[mod_name] = mock.Mock()

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

todo_include_todos = True

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# -- HTML Theme ---------------------------------------------------
#html_theme = 'sphinx_rtd_theme'
#html_theme = 'pydata_sphinx_theme'
html_theme = 'bizstyle'
#html_theme = 'pyramid'
#html_theme = 'nature'
#html_theme = 'haiku'
#html_theme = 'alabaster'

html_logo = "logotopo.jpg"
html_theme_options = {
    'logo_only': True,
    'display_version': False,
}


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

